name: PipelineWorkflow
on:
  push:
	branches:
	  - master
  pull_request:
	branches:
	  - master

jobs:
    build:
	  runs-on: ubuntu-latest
	  steps:
	  - name: Azure Pipeline
		uses: Azure/pielines@v1
		with:
		  azure-devops-project-url: https://dev.azure.com/ramansharma95/MyProjecct
		  azure-devops-pipeline-name: 'Ascendion-raman '
		  azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
